import re

# ── OCR noise corrections (scanned PDFs) ──────────────────────────────────────
_OCR_FIXES = [
    (r'\bGSTIN\s+el\s+Supp\w*',                     'GSTIN of Supplier'),
    (r'\bGSTIN\s+ol\s+Rec\w*',                      'GSTIN of Recipient'),
    (r'\bP[il]ace\s+of\s+D\s*sp[a-zA-Z]+',          'Place of Dispatch'),
    (r'\bPla[co]{2}\s+0?[1Oo]\s+D\w+ry\b',          'Place of Delivery'),
    (r'\bE-?W[ae]y\s+B[iI][iI]\s+D[ao][il][ae]\b',  'E-Way Bill Date'),
    (r'\bE-?W[ae]y\s+B[iI][iI]\s+N[o0]\b',          'E-Way Bill No'),
    (r'\bBWy\s+0U\s+No\b',                           'E-Way Bill No'),
    (r'\bVal[yd][oc]\s+[0O]f\s+Goods\b',             'Value of Goods'),
    (r'\bHSN\s+Cod[o0]\b',                           'HSN Code'),
    (r'\bTrnspon[tn]er\b',                           'Transporter'),
    (r'\bDocum[ae]n[tl]\s+No\.',                     'Document No.'),
    (r'\bDocum[oa][mn][tl]\s+D[ao][lt][ae]\b',       'Document Date'),
    (r'\bTran[ae][ao][oc]t[o0][on]\s+Ty[lp][ae]\b',  'Transaction Type'),
    (r'\bGon[ae]r[ao]l[oa]d\s+BY[a-z]?\b',          'Generated By'),
    (r'\bVelid\s+Fr[oa][mn]\b',                      'Valid From'),
    (r'\bVelid\s+Un[it][il]\b',                      'Valid Until'),
    (r'\bVanj\s+Unti\b',                             'Valid Until'),
    (r'\bOulward\b',                                 'Outward'),
    (r'\bRo[nm]d\b',                                 'Road'),
    (r'(\d{2})\.(\d{2})\s*(AM|PM)',                  r'\1:\2 \3'),
    (r'\bBIll\s+To\s+Shlp\s+To\b',                  'Bill To - Ship To'),
    (r'\bBill\s+To\s+Shlp\s+To\b',                  'Bill To - Ship To'),
    (r'\bReason\s+fo[r:.]+\s+\w*[Tt]ation\b',        'Reason for Transportation'),
]


def _fix_ocr(text: str) -> str:
    for pat, rep in _OCR_FIXES:
        text = re.sub(pat, rep, text, flags=re.IGNORECASE)
    return text


def _find(pattern, text, default=""):
    match = re.search(pattern, text, re.IGNORECASE)
    return match.group(1).strip() if match else default


def _find_any(patterns, text, default=""):
    """Try multiple patterns and return the first match found."""
    for pattern in patterns:
        match = re.search(pattern, text, re.IGNORECASE)
        if match:
            return match.group(1).strip()
    return default


def _clean_gstin(raw):
    return raw.replace(" ", "").strip()


def _parse_place_line(line):
    """Parse 'City,STATE-PINCODE' into (city, state, pin)."""
    line = line.strip()
    m = re.match(r"^,?(.+?),([A-Z][A-Z ]+)-(\d{6})", line)
    if m:
        return m.group(1).strip(), m.group(2).strip(), m.group(3).strip()
    # OCR fallback: space after comma, or corrupted pincode digit (e.g. J82130)
    m = re.match(r"^,?(.+?),\s*([A-Z][A-Z ]+)-([A-Z0-9]{6})", line)
    if m:
        pin = re.sub(r'[^0-9]', '', m.group(3))
        return m.group(1).strip(), m.group(2).strip(), pin
    return line, "", ""


def _extract_place_from_block(block):
    """Find city, state, pincode from the last STATE-PINCODE pattern in an address block."""
    if not block:
        return "", "", ""
    # Standard: CITY,STATE-PINCODE
    matches = re.findall(r",?([A-Za-z][A-Za-z ]+),([A-Z][A-Z ]+)-(\d{6})", block)
    if matches:
        last = matches[-1]
        return last[0].strip(), last[1].strip(), last[2].strip()
    m = re.search(r"([A-Za-z][A-Za-z ]+),([A-Z][A-Z ]+)-(\d{6})", block)
    if m:
        return m.group(1).strip(), m.group(2).strip(), m.group(3).strip()
    # OCR fallback: pincode may have a corrupted first digit (e.g. J82130 → 82130)
    m = re.search(r"([A-Za-z][A-Za-z ]+),([A-Z][A-Z ]+)-([A-Z0-9]{6})", block)
    if m:
        pin = re.sub(r'[^0-9]', '', m.group(3))  # strip OCR noise, keep digits
        return m.group(1).strip(), m.group(2).strip(), pin
    # Fallback: "CITY STATE PINCODE" (no comma/dash separators)
    m = re.search(r"([A-Za-z][A-Za-z ]+)\s+([A-Z]{5,20})\s+(\d{6})", block)
    if m:
        return m.group(1).strip(), m.group(2).strip(), m.group(3).strip()
    return block.strip()[:50], "", ""


def _is_eway_bill(text: str) -> bool:
    """Check if the document is a valid E-Way Bill."""
    indicators = [
        r"e-?way\s*bill",
        r"eway\s*bill",
        r"ewb\s*no",
        r"gstin\s*of\s*supplier",
        r"place\s*of\s*dispatch",
        r"Part\s*-?\s*B",
    ]
    return any(re.search(p, text, re.IGNORECASE) for p in indicators)


def parse_eway_bill(text: str) -> dict:
    t = re.sub(r'\s+', ' ', text).strip()
    t = _fix_ocr(t)

    if not _is_eway_bill(t):
        raise ValueError("Please upload valid e way bill document")

    # ── EWB Number ────────────────────────────────────────────────────────────
    ewb_no_raw = _find_any([
        r"E-?Way\s*Bill\s*No[:\s]+([0-9][\s0-9]{10,14}[0-9])",
        r"eWay\s*Bill\s*No[:\s]+([0-9][\s0-9]{10,14}[0-9])",
        r"EWB\s*No[:\s]+([0-9][\s0-9]{10,14}[0-9])",
        r"E-?Way\s*Bill\s*No[:\s]+([0-9JOI][\sJOI0-9]{8,14}[0-9JOI])",  # OCR fallback
    ], t)
    ewb_no = re.sub(r'[^0-9]', '', ewb_no_raw)

    # ── EWB Date ──────────────────────────────────────────────────────────────
    ewb_date = _find_any([
        r"E-?Way\s*Bill\s*Date[:\s]+([0-9]{2}/[0-9]{2}/[0-9]{4}(?:\s+\d{1,2}:\d{2}(?::\d{2})?\s*[APM]{2})?)",
        r"Generated\s*Date[:\s]+([0-9]{2}/[0-9]{2}/[0-9]{4}(?:\s+\d{1,2}:\d{2}(?::\d{2})?\s*[APM]{2})?)",
        r"EWB\s*Date[:\s]+([0-9]{2}/[0-9]{2}/[0-9]{4}(?:\s+\d{1,2}:\d{2}(?::\d{2})?\s*[APM]{2})?)",
    ], t)

    # ── Valid From ────────────────────────────────────────────────────────────
    valid_from = _find_any([
        r"Valid\s*From[:\s]+([0-9]{2}/[0-9]{2}/[0-9]{4}(?:\s+\d{1,2}:\d{2}(?::\d{2})?\s*[APM]{2})?)",
    ], t)

    # ── Valid Till ────────────────────────────────────────────────────────────
    valid_till = _find_any([
        r"Valid\s*(?:Until|Till|Upto|Up\s*to)[:\s]+([0-9]{2}/[0-9]{2}/[0-9]{4}(?:\s+\d{1,2}:\d{2}(?::\d{2})?\s*[APM]{2})?)",
        r"Validity[:\s]+([0-9]{2}/[0-9]{2}/[0-9]{4})",
    ], t)

    # ── Generated By ─────────────────────────────────────────────────────────
    generated_by_gstin = _find_any([
        r"Generated\s*By[:\s]+([A-Z0-9]+)\s*-",   # "GSTIN - Name" format
        r"Generated\s*By[:\s]+([A-Z0-9]{15})\b",  # GSTIN only (no name)
    ], t)
    if generated_by_gstin:
        generated_by_gstin = _clean_gstin(generated_by_gstin)
    gen_m = re.search(r"Generated\s*By[:\s]+[A-Z0-9]+\s*-\s*(.+?)(?=Valid|IRN|Part)", t, re.IGNORECASE)
    generated_by_name = gen_m.group(1).strip() if gen_m else ""

    # ── Supply Type ───────────────────────────────────────────────────────────
    supply_type = _find_any([
        r"Supply\s*Type[:\s]+([A-Za-z ]+?)(?=\s+\w)",
        r"Type[:\s]+(Outward[A-Za-z\-]*|Inward[A-Za-z\-]*)",
        r"Reason\s*for\s*Transpo[a-z]+\s+(Outward|Inward)",
    ], t)

    # ── Transaction Type ──────────────────────────────────────────────────────
    trans_type = _find_any([
        r"Transaction\s*Type[:\s]+(.+?)(?=\s+IRN|\s+Document\s*(?:No|Details|Date)|\s+Value\s*of)",
        r"Transaction\s*Type[:\s]+([A-Za-z0-9 \-]+)",
    ], t)

    # ── Document Details ──────────────────────────────────────────────────────
    # Format 2: separate "Document No." and "Document Date"
    # Format 1: "Document Details: Tax Invoice - HY25001900 - 30/03/2026"
    doc_no = _find_any([
        r"Document\s*No\.?\s+([A-Z0-9/\-]+)",
        r"Document\s*Details[:\s]+[A-Za-z ]+?\s*-\s*([A-Z0-9/]+)\s*-\s*[0-9]{2}/[0-9]{2}/[0-9]{4}",
    ], t)

    doc_date = _find_any([
        r"Document\s*Date\s+([0-9]{2}/[0-9]{2}/[0-9]{4})",
        r"Document\s*Details[:\s]+[A-Za-z ]+?\s*-\s*[A-Z0-9/]+\s*-\s*([0-9]{2}/[0-9]{2}/[0-9]{4})",
    ], t)

    doc_type = _find_any([
        r"Document\s*Type[:\s]+([A-Za-z ]+?)(?=\s+\w)",
        r"Document\s*Details[:\s]+([A-Za-z ]+?)\s*-\s*[A-Z0-9]",
    ], t)

    # ── Value of Goods (taxable) and Total Invoice Value ─────────────────────
    value_goods = _find_any([
        r"Value\s*of\s*Goods\s+([0-9,]+(?:\.[0-9]+)?)",
        r"Tot(?:al)?\.?\s*Taxable\s*Amt[:\s]*Rs\.([0-9,]+(?:\.[0-9]+)?)",
    ], t)
    total_inv_value = _find_any([
        r"Total\s*Inv(?:oice)?\.?\s*Amt[:\s]*Rs\.([0-9,]+(?:\.[0-9]+)?)",
        r"Invoice\s*Value[:\s]*Rs\.([0-9,]+(?:\.[0-9]+)?)",
    ], t) or value_goods

    # ── IRN ───────────────────────────────────────────────────────────────────
    irn = _find(r"IRN[:\s]+([a-f0-9]{64})", t)

    # ── Reason ────────────────────────────────────────────────────────────────
    reason = _find_any([
        r"Reason\s*for\s*Transportation\s+(.+?)(?=Transporter)",
        r"Reason\s*for\s*Transport[:\s]+(.+?)(?=Transporter|Part\s*[AB])",
    ], t)

    # ── From Party ────────────────────────────────────────────────────────────
    from_gstin = ""
    from_name  = ""
    from_place, from_state, from_pin = "", "", ""

    # Format 2: "GSTIN of Supplier 27AAICP0247K1Z9,Porite India..."
    from_gstin_raw = _find(r"GSTIN\s*of\s*Supplier\s+([A-Z0-9 ]+),", t)
    if from_gstin_raw:
        from_gstin    = _clean_gstin(from_gstin_raw)
        from_name     = _find(r"GSTIN\s*of\s*Supplier\s+[A-Z0-9 ]+,(.+?)(?=Place\s*of\s*Dispatch)", t)
        dispatch_raw  = _find(r"Place\s*of\s*Dispatch\s+(.+?)(?=GSTIN\s*of\s*Recipient)", t)
        from_place, from_state, from_pin = _parse_place_line(dispatch_raw)
    else:
        # Format 1: "From GSTIN : 36AAACJ1494Q1Z1 NAME STATE ::Dispatch From:: address"
        from_gstin_raw = _find(r"From\s+GSTIN\s*:\s*([A-Z0-9]+)", t)
        from_gstin     = _clean_gstin(from_gstin_raw)
        from_name      = _find(r"From\s+GSTIN\s*:\s*[A-Z0-9]+\s+(.+?)(?=::Dispatch\s*From::)", t)
        if from_name:
            from_name  = re.sub(r'\s+[A-Z]{4,}\s*$', '', from_name).strip()
        dispatch_raw   = _find(r"::Dispatch\s*From::\s*(.+?)(?=To\s+GSTIN|\bTo\b)", t)
        from_place, from_state, from_pin = _extract_place_from_block(dispatch_raw)
        if not from_place and dispatch_raw:
            _fb = re.search(r',([A-Za-z][A-Za-z0-9 ]+),([A-Z][A-Z ]+)-(\d{6})', dispatch_raw)
            if _fb:
                from_place = _fb.group(1).strip()
                if not from_state: from_state = _fb.group(2).strip()
                if not from_pin:   from_pin   = _fb.group(3).strip()

    # ── To Party ──────────────────────────────────────────────────────────────
    to_gstin = ""
    to_name  = ""
    to_place, to_state, to_pin = "", "", ""

    # Format 2: "GSTIN of Recipient 33AAACK5968J3Z7,Astemo..."
    to_gstin_raw = _find(r"GSTIN\s*of\s*Recipient\s+([A-Z0-9 ]+)\s*,", t)
    if to_gstin_raw:
        to_gstin     = _clean_gstin(to_gstin_raw)
        to_name      = _find(r"GSTIN\s*of\s*Recipient\s+[A-Z0-9 ]+\s*,(.+?)(?=Place\s*of\s*Delivery)", t)
        delivery_raw = _find(r"Place\s*of\s*Delivery\s+(.+?)(?=Document\s*No)", t)
        to_place, to_state, to_pin = _parse_place_line(delivery_raw)
    else:
        # Format 1: "To GSTIN : 06AAOCM1740Q1ZY NAME STATE ::Ship To:: address"
        to_gstin_raw = _find(r"To\s+GSTIN\s*:\s*([A-Z0-9]+)", t)
        to_gstin     = _clean_gstin(to_gstin_raw)
        to_name      = _find(r"To\s+GSTIN\s*:\s*[A-Z0-9]+\s+(.+?)(?=::Ship\s*To::)", t)
        if to_name:
            to_name  = re.sub(r'\s+[A-Z]{4,}\s*$', '', to_name).strip()
        delivery_raw = _find(r"::Ship\s*To::\s*(.+?)(?=3\.\s*Goods|Goods\s*Details?|\Z)", t)
        to_place, to_state, to_pin = _extract_place_from_block(delivery_raw)

    # ── Item Details ──────────────────────────────────────────────────────────
    # Format 2: "HSN Code 87089900 - PRODUCT NAME"
    hsn_codes = re.findall(r'HSN\s*Code\s+(\d{4,8})', t, re.IGNORECASE)
    _raw_prods = re.findall(
        r'HSN\s*Code\s+\d{4,8}\s*-\s*([A-Za-z][A-Za-z0-9 /,\-\.]{2,80}?)(?=\s*(?:HSN|Reason|Taxable|Rate|Transporter|Part\s*-?\s*[AB])|\Z)',
        t, re.IGNORECASE
    )
    _doc_keywords = {'reason', 'transporter', 'part', 'valid', 'gstin', 'document', 'value', 'irn', 'portal', 'place', 'supply', 'transaction'}
    products = [
        p.strip() for p in _raw_prods
        if p.strip()
        and len(p.strip()) <= 80
        and p.strip().split()[0].lower() not in _doc_keywords
    ]

    if not hsn_codes:
        # Format 1: HSN codes appear in goods table as standalone 8-digit numbers
        goods_section = _find(r'Goods\s*Details?\s+(.+?)(?:Transportation\s*Details?|Transporter\s*ID|\Z)', t)
        if goods_section:
            # Only match 8-digit numbers — amounts are 6-7 digits, HSN codes are 8
            hsn_codes = re.findall(r'\b(\d{8})\b', goods_section)
            # Product name is between HSN code and the quantity like "13.74 (TON)"
            prods = re.findall(r'\b\d{8}\b\s+([A-Za-z][\w\s\-\.\/]+?)(?=\s+\d+\.\d+\s*\()', goods_section)
            products = [p.strip() for p in prods if p.strip()]

    # Tax amounts
    taxable_value = _find_any([
        r"Tot(?:al)?\.?\s*Taxable\s*Amt[:\s]*Rs\.([0-9,]+(?:\.[0-9]+)?)",
        r"Taxable\s*(?:Amount|Value|Amt)[:\s]*(?:Rs\.)?([0-9,]+(?:\.[0-9]+)?)",
    ], t) or value_goods
    cgst = _find(r"CGST\s*(?:Amt|Amount|Rate)[:\s]*(?:Rs\.)?([0-9,]+(?:\.[0-9]+)?)", t)
    sgst = _find(r"SGST\s*(?:Amt|Amount|Rate)[:\s]*(?:Rs\.)?([0-9,]+(?:\.[0-9]+)?)", t)
    igst = _find(r"IGST\s*(?:Amt|Amount|Rate)[:\s]*(?:Rs\.)?([0-9,]+(?:\.[0-9]+)?)", t)

    # ── Transporter ───────────────────────────────────────────────────────────
    trans_id_raw = _find_any([
        # Format 1: "Transporter ID & Name: 36AAFCK1245B1Z1 & KSS ROADWAYS..."
        r"Transporter\s+ID\s*&\s*Name[:\s]+([A-Z0-9]+)\s*[&%]",
        # Format 2: "Transporter 27AAGCV1179G1Z5 & Vivanta..."  (% = OCR for &)
        r"Transporter\s+([A-Z0-9 ]+)\s*[&%]",
    ], t)
    trans_id   = _clean_gstin(trans_id_raw)

    trans_name = _find_any([
        # Format 1: "Transporter ID & Name: GSTIN & KSS ROADWAYS..."
        r"Transporter\s+ID\s*&\s*Name[:\s]+[A-Z0-9]+\s*[&%]\s*(.+?)(?=Transporter\s*Doc|Vehicle\s*Details?|\Z)",
        # Format 2: "Transporter GSTIN & Vivanta..."  (% = OCR for &)
        r"Transporter\s+[A-Z0-9 ]+\s*[&%]\s*(.+?)(?=Part\s*-\s*[AB]|\Z)",
    ], t)

    # ── Vehicle and Transport Mode ────────────────────────────────────────────
    transport_entries = []

    # Indian vehicle number: 2 letters + 1-2 digits + 1-3 letters + 4 digits (hyphens optional)
    # Lookbehind/ahead prevents false matches inside 15-char GSTINs
    # [0-9OI] allows OCR-confused O→0 and I→1 in the district digit positions
    _VEH_RE  = r'(?<![A-Z0-9])([A-Z]{2}[\-]?[0-9OI]{1,2}[\-]?[A-Z]{1,3}[\-]?\d{4})(?![A-Z0-9])'
    _MODE_RE = r'(Road|Rail|Air|Ship)'
    # Date supports both DD/MM/YYYY and DD-MM-YYYY, with optional time
    _DATE_RE = r'(\d{2}[\/\-]\d{2}[\/\-]\d{4}(?:\s+\d{1,2}:\d{2}(?::\d{2})?\s*[APM]{2})?)'

    def _clean_vno(v):
        v = re.sub(r'[\-]', '', v).upper()
        # Fix OCR digit substitutions in the district number (positions 2-4 after state code)
        v = re.sub(
            r'^([A-Z]{2})([OI0-9]{1,2})([A-Z]{1,3})(\d{4})$',
            lambda m: m.group(1)
                      + m.group(2).replace('O', '0').replace('I', '1')
                      + m.group(3) + m.group(4),
            v
        )
        return v

    def _norm_date(d):
        return d.replace('-', '/') if d else d

    part_b       = _find(r"Part\s*-?\s*B\s+(.+)", t)
    search_scope = part_b if part_b else t

    # ── Layer 1a: Part B table — Mode before vehicle (most common)
    # Row order: Mode  VehicleNo  [From]  Date  EnteredBy  [CEWBNo]
    if part_b:
        # With from_place between vehicle and date
        # Also handles "& - & -" doc-info token between vehicle number and from_place
        row_pat_with_place = (
            r'\b' + _MODE_RE + r'\s+'
            + _VEH_RE + r'(?:\s+&[^A-Za-z]{0,30})?\s+'
            r'([A-Za-z][A-Za-z0-9\-/ ]+?)(?=\s+\d{2}[\/\-]\d{2}[\/\-]\d{4})\s+'
            + _DATE_RE + r'\s+'
            r'([A-Z0-9]+)'
            r'(?:\s+(\d{8,12}))?'
        )
        # Without from_place (vehicle number directly before date)
        row_pat_no_place = (
            r'\b' + _MODE_RE + r'\s+'
            + _VEH_RE + r'\s+'
            + _DATE_RE + r'\s+'
            r'([A-Z0-9]+)'
            r'(?:\s+(\d{8,12}))?'
        )
        found_in_1a = set()
        for row in re.findall(row_pat_with_place, part_b, re.IGNORECASE):
            vno = _clean_vno(row[1])
            transport_entries.append({
                "vehicle_number":   vno,
                "transport_doc_no": "",
                "transport_mode":   row[0].capitalize(),
                "from_place":       row[2].strip(),
                "entered_date":     _norm_date(row[3].strip()),
                "entered_by":       row[4].upper(),
                "cewb_number":      row[5] if row[5] else "",
            })
            found_in_1a.add(vno)
        for row in re.findall(row_pat_no_place, part_b, re.IGNORECASE):
            vno = _clean_vno(row[1])
            if vno in found_in_1a:
                continue
            transport_entries.append({
                "vehicle_number":   vno,
                "transport_doc_no": "",
                "transport_mode":   row[0].capitalize(),
                "from_place":       "",
                "entered_date":     _norm_date(row[2].strip()),
                "entered_by":       row[3].upper(),
                "cewb_number":      row[4] if row[4] else "",
            })
            found_in_1a.add(vno)

    # ── Layer 1b: "Vehicle No: MH12AB1234  Mode: Road" label format
    if part_b:
        label_pat = (
            r'Vehicle\s*(?:No\.?|Number)[:\s]+' + _VEH_RE
            + r'(?:[^a-z]{0,40}Mode[:\s]+' + _MODE_RE + r')?'
            + r'(?:[^a-z]{0,60}(?:From|Dispatch)[:\s]+([A-Z][A-Z0-9 \-]+?)(?=\s+\d{2}[\/\-]|\s+[A-Z0-9]{15}|\s+Mode|\s+Date))?'
            + r'(?:[^a-z]{0,60}(?:Entered\s*)?Date[:\s]+' + _DATE_RE + r')?'
            + r'(?:[^a-z]{0,60}(?:Entered\s*By|GSTIN)[:\s]+([A-Z0-9]+))?'
        )
        lbl_found = {e["vehicle_number"] for e in transport_entries}
        for row in re.findall(label_pat, part_b, re.IGNORECASE):
            vno = _clean_vno(row[0])
            if vno in lbl_found:
                continue
            transport_entries.append({
                "vehicle_number":   vno,
                "transport_doc_no": "",
                "transport_mode":   row[1].capitalize() if row[1] else "",
                "from_place":       row[2].strip() if row[2] else "",
                "entered_date":     _norm_date(row[3].strip()) if row[3] else "",
                "entered_by":       row[4].upper() if row[4] else "",
                "cewb_number":      "",
            })
            lbl_found.add(vno)

    # ── Layer 1c: Rail/Air/Ship with transport doc number instead of vehicle number
    if part_b:
        doc_row_pat = (
            r'\b(Rail|Air|Ship)\s+'
            r'([A-Z0-9][A-Z0-9/\-]{4,24})\s+'
            r'([A-Z][A-Z0-9\-/ ]+?)(?=\s+\d{2}[\/\-]\d{2}[\/\-]\d{4})\s+'
            + _DATE_RE + r'\s+'
            r'([A-Z0-9]+)'
            r'(?:\s+(\d{8,12}))?'
        )
        for row in re.findall(doc_row_pat, part_b, re.IGNORECASE):
            transport_entries.append({
                "vehicle_number":   "",
                "transport_doc_no": row[1].upper(),
                "transport_mode":   row[0].capitalize(),
                "from_place":       row[2].strip(),
                "entered_date":     _norm_date(row[3].strip()),
                "entered_by":       row[4].upper(),
                "cewb_number":      row[5] if row[5] else "",
            })

    # ── Layer 2: safety net — any vehicle number in scope not yet captured
    found = {e["vehicle_number"] for e in transport_entries if e["vehicle_number"]}
    for raw_vno in list(dict.fromkeys(re.findall(_VEH_RE, search_scope, re.IGNORECASE))):
        vno = _clean_vno(raw_vno)
        if vno in found:
            continue
        ctx_m   = re.search(r'(.{0,100})' + re.escape(raw_vno) + r'(.{0,200})', search_scope, re.IGNORECASE)
        ctx     = (ctx_m.group(1) + raw_vno + ctx_m.group(2)) if ctx_m else raw_vno
        mode_m  = re.search(_MODE_RE, ctx, re.IGNORECASE)
        date_m  = re.search(_DATE_RE, ctx)
        gstin_m = re.search(r'\b([A-Z0-9]{15})\b', ctx)
        # Try positional: text between vehicle number and date (table format)
        pos_m   = re.search(
            re.escape(raw_vno) + r'(?:\s+&[^A-Za-z]{0,30})?\s+([A-Za-z][A-Za-z0-9\-/ ]*?)(?=\s+\d{2}[\/\-]\d{2}[\/\-]\d{4})',
            ctx, re.IGNORECASE
        )
        # Fallback: labeled "From: PLACE" format
        lbl_m   = re.search(
            r'(?:From|Dispatch)[:\s]+([A-Za-z][A-Za-z0-9 \-]+?)(?=\s+\d{2}[\/\-]|\s+[A-Z0-9]{15})',
            ctx, re.IGNORECASE
        )
        _veh_from = (pos_m.group(1).strip() if pos_m else "") or (lbl_m.group(1).strip() if lbl_m else "")
        transport_entries.append({
            "vehicle_number":   vno,
            "transport_doc_no": "",
            "transport_mode":   mode_m.group(1).capitalize() if mode_m else "",
            "from_place":       _veh_from,
            "entered_date":     _norm_date(date_m.group(1).strip()) if date_m else "",
            "entered_by":       gstin_m.group(1) if gstin_m else "",
            "cewb_number":      "",
        })
        found.add(vno)

    # ── Layer 3: no Part B at all — scan full document
    if not transport_entries:
        mode_m      = re.search(r"\bMode[:\s]+" + _MODE_RE, t, re.IGNORECASE)
        global_mode = mode_m.group(1).capitalize() if mode_m else ""
        for raw_vno in list(dict.fromkeys(re.findall(_VEH_RE, t, re.IGNORECASE))):
            ctx_m   = re.search(r'(.{0,100})' + re.escape(raw_vno) + r'(.{0,200})', t, re.IGNORECASE)
            ctx     = (ctx_m.group(1) + raw_vno + ctx_m.group(2)) if ctx_m else raw_vno
            mode_m2 = re.search(_MODE_RE, ctx, re.IGNORECASE)
            date_m  = re.search(_DATE_RE, ctx)
            transport_entries.append({
                "vehicle_number":   _clean_vno(raw_vno),
                "transport_doc_no": "",
                "transport_mode":   mode_m2.group(1).capitalize() if mode_m2 else global_mode,
                "from_place":       "",
                "entered_date":     _norm_date(date_m.group(1).strip()) if date_m else "",
                "entered_by":       "",
                "cewb_number":      "",
            })

    return {
        "ewb_details": {
            "ewb_number":           ewb_no,
            "ewb_date":             ewb_date,
            "valid_from":           valid_from,
            "valid_till":           valid_till,
            "generated_by_gstin":   generated_by_gstin,
            "generated_by_name":    generated_by_name,
            "supply_type":          supply_type,
            "transaction_type":     trans_type,
            "document_number":      doc_no,
            "document_date":        doc_date,
            "document_type":        doc_type,
            "value_of_goods":       value_goods,
            "reason_for_transport": reason.strip() if reason else "",
            "irn":                  irn,
        },
        "from_party": {
            "gstin":   from_gstin,
            "name":    from_name.strip() if from_name else "",
            "place":   from_place,
            "state":   from_state,
            "pincode": from_pin,
        },
        "to_party": {
            "gstin":   to_gstin,
            "name":    to_name.strip() if to_name else "",
            "place":   to_place,
            "state":   to_state,
            "pincode": to_pin,
        },
        "item_details": {
            "hsn_codes":     hsn_codes,
            "products":      [p.strip() for p in products],
            "taxable_value": taxable_value,
            "cgst_rate":     cgst,
            "sgst_rate":     sgst,
            "igst_rate":     igst,
            "total_value":   total_inv_value,
        },
        "transporter_details": {
            "transporter_id":   trans_id,
            "transporter_name": trans_name.strip() if trans_name else "",
            "transport_entries": transport_entries,
        },
    }
